### PR TITLE
run in colab

### PR DESCRIPTION
**Pull request by jburel**
* example indicating what do to if running the notebook in Colab
* To test:
  * go to https://colab.research.google.com/notebooks/intro.ipynb#recent=true
  * File> Open notebook
  * Select GitHub
  * Enter jburel/omero-guide-python
  * Select the colab branch
  * Open the ``CalculateSharpnessOneImage.ipynb``.
  * The cell installing omero-py will take time (mainly due to ice python)
  * If the cell is run when using mybinder, nothing will be updated.
  

cc @pwalczysko

### CODE REVIEW

**Comment by jburel** [comment]
If we decide to move forward with this approach, i will add badge, review other notebooks etc.

**Comment by pwalczysko** [comment]
the noebook on colab works fine. the only RFE would be to add a valid image ID into the notebook calculatesharpness by default, but I guess it might not be even for this PR. The suggested default image ID might be 11270 

the notebook on MyBinder worked fine too, the first cell was executable and ended with message like "already installed".

I think this approach is fine as outlined in this PR, if it brings more users as we have indications it would, I am all for it.

**Comment by jburel** [comment]
I will update the id and check the other notebooks, add links etc.

**Comment by pwalczysko** [comment]
1. Default image ids to change (suggested id in the bracket) for **illumination correction** notebook (11270)

2. **HelloWordl** notebook produces output ending with 
```
object #0 (::omero::RLong)
{
    _val = 11082
}
```
maybe improve by printing the value only, not the RLong object ?

3. **Simple FRAP** notebook:

There is a need to insert first the correct Image ID and then, to insert the correct channel name. Suggest to at least give the channel name options, as I had to go twice to webclient to get the correct parameters. For the image ID it could be 28662, the channel name is 528.0 but as indicated, better to offer the channel names in the dropdown imho.

**Comment by jburel** [comment]
@pwalczysko other than those small improvements, everything works in Colab?

**Comment by pwalczysko** [comment]
> @pwalczysko other than those small improvements, everything works in Colab?

Principally it looks good, but far from done yet, as the system rejects parallel execution of several notebooks.

**Comment by pwalczysko** [comment]
Bug: 
The notebook **zarr-public-s3-multiscale_1.ipynb** is not working, erroring

```
ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-2-e4d9beb43c66> in <module>()
      3 from matplotlib import pyplot as plt
      4 import requests
----> 5 import zarr
      6 # package for 3d visualization
      7 from itkwidgets import view

ModuleNotFoundError: No module named 'zarr

```

It seems to me this could be caused by the missing ``pip install ...`` code cell just above. 

Also, wondering what is the difference between this notebook and the other zarr notebook, which is named the same but without the numeral ``_1`` at the end of the name ? 

Edit:
Analogous problem with the notebook **zarr-public-s3-segmentation-parallel_1.ipynb**. Again, confused by the ``_1`` and the duplication - the notebook does crash on the importing of libraries, as the pip install step is missing similar to the **zarr-public-s3-multiscale_1.ipynb** case

**Comment by pwalczysko** [comment]
In summary, works nicely, just a couple of RFEs https://github.com/ome/omero-guide-python/pull/32#issuecomment-802803638 and the problem with the ``_1`` notebooks https://github.com/ome/omero-guide-python/pull/32#issuecomment-802925136

**Comment by jburel** [comment]
@pwalczysko The notebook zarr-public-s3-multiscale_1.ipynb should not have been committed

**Comment by jburel** [comment]
@pwalczysko everything should be sorted now

**Comment by pwalczysko** [comment]
Tested new commits:

 - Illumination correction notebook with the new ID - as expected
 - HelloWorld notebook with the new image ID output fix - as expected
 - FRAP notebook with the new channel selection - as expected

The ``_1`` notebooks are not there anymore, as expected.

Ready to merge fmpov

**Pull request merged**
