### PR TITLE
Migrate maintenance

### PR DESCRIPTION
**Pull request by jburel**
* migrate the python scripts from https://github.com/ome/training-scripts/tree/master/maintenance/scripts
* review the script so the password is hidden
cc @pwalczysko @will-moore

### CODE REVIEW

**Comment by joshmoore** [comment]
Two thoughts:
 - is this the repository where the train-the-trainers work will be consolidated? These scripts are of special interest in those cases?
 - And if so, it might make sense to package (and version) them separately since people will want to use them perhaps without git cloning this repository.

cc: @sbesson

**Comment by jburel** [comment]
I was thinking to add doc pages & notebooks for "train-the-trainers" to show how to run some features in the script e.g. how to tag
but there is also the need for a "utils" package since a lot of those functions are very common

**Comment by pwalczysko** [comment]
What will happen if somebody has a link to the present repo such as highlighted in https://downloads.openmicroscopy.org/presentations/2020/Munster/OMERO-workshop/#/6 ?

Will that link simply break after the migration ?

**Comment by jburel** [comment]
No the file will stay in training-scripts repo. I don't see us updating those script in training-repo
I am planning to add info in readme indicating where the files have been "dispatched"

**Comment by pwalczysko** [comment]
Built this PR locally using repo2docker.

After that, started a new terminal, went to a scripts folder and activated the ``notebooks`` conda env.
After that, I was able to successfully execute the ``delete_ROIs.py`` script.

This looks like a good first step to me.

**Comment by joshmoore** [comment]
> I was thinking to add doc pages & notebooks for "train-the-trainers" to show how to run some features in the script e.g. how to tag

i.e., so this repo is the home for train-the-trainers, at least for the time being?

> but there is also the need for a "utils" package since a lot of those functions are very common

Where do you see this living?

**Comment by jburel** [comment]
> > I was thinking to add doc pages & notebooks for "train-the-trainers" to show how to run some features in the script e.g. how to tag
> 
> i.e., so this repo is the home for train-the-trainers, at least for the time being?
I would think so
> 
> > but there is also the need for a "utils" package since a lot of those functions are very common
> 
> Where do you see this living?
something like ome/omero-py-utils

**Comment by sbesson** [comment]
Following https://github.com/ome/omero-guide-python/pull/23#issuecomment-671215884, my understanding of the intent of this PR is the migration the Python scripts used for managing the training server into the how-to guides for the Python API.  Given how generic the guide is and how specific these scripts are, I am also unclear about the decision process for which custom Python scripts can or should be migrated to this repository as well as the long-term strategy for exposing these scripts in the guide itself.

Re util packages, I am in favor of identifying and migrating common logic upstream. More specifics might be needed but we might need to balance the cost of adding (and maintaining) yet-another-intermediate-Python-package vs simply extending the gateway. Independently of the solution, if some functionality is extracted elsewhere, we will probably need to look into capturing the dependency relationship and naturally consider the packaging of these scripts.

**Comment by jburel** [comment]
Those scripts are certainly used to manage our training servers. From the feedback we collected, more people are asking for this type of examples to manage their own resources i.e. not as custom as one would think. As indicating migrating the script is the first step so we can then start writing doc and notebooks. We have been asked when possible to have notebook for presentation and script so people can "take" them and run.

**Comment by joshmoore** [comment]
> We have been asked when possible to have notebook for presentation and script so people can "take" them and run.

But doesn't that imply having them also _outside_ of a notebook?

**Comment by jburel** [comment]
Both notebooks and scripts.
I will close this for now and propose a possible evolution

**Comment by jburel** [comment]
@pwalczysko @will-moore following the successful "Train the trainers" workshop
we should probably re-activate that work and decide where we want it to be. Either keep in the training-scipts and turn the repo into a guide. It might be cleaner to start a new repo since the training-scripts still has old content (migrated to guides)

**Comment by pwalczysko** [comment]
> ...since the training-scripts still has old content (migrated to guides)

Not sure I understand. Is the old content migrated to guides ? Is the "new" content migrated ? (not afaik) We discussed this morning during standup, I thought that all the training-scripts will be migrated to guides or idr studies repos ? 
cc @sbesson @joshmoore @will-moore

**Comment by jburel** [comment]
We have migrated the content under https://github.com/ome/training-scripts/tree/master/practical. This is indicated in the README but we have kept the original so we do not break previous training session (pdf) linking to those files
The content under ``maintenance`` **has not** been migrated. That was the initial purpose of this PR
We now need to decide what to merge and where as we did for the practical examples.
Question: do we create a dedicated guide "train the trainers"? where a lot of the content under ``maintenance`` could actually go

**Comment by pwalczysko** [comment]
> Question: do we create a dedicated guide "train the trainers"? where a lot of the content under maintenance could actually go

I think yes, also got that feeling from the participants feedback on the OME 2021 that a dedicated guide was asked for.

**Pull request closed without merging**
