### PR TITLE
Idr0021

### PR DESCRIPTION
**Pull request by jburel**
Add example using idr0021 in the spirit of https://github.com/ome/omero-guide-r/blob/master/notebooks/idr0021_Segmentation-noSave.ipynb

cc @will-moore

### CODE REVIEW

**Comment by pwalczysko** [comment]
No problem with running this in MyBinder.
Google collab shows error on the cell

```
statistics = {
    'area':       [p.area               for p in properties],
    'mean':       [p.mean_intensity     for p in properties],
    'major_axis': [p.major_axis_length  for p in properties],
    'perimeter' : [p.perimeter          for p in properties],
    'orientation' :  [p.orientation          for p in properties],
    'eccentricity':  [p.eccentricity          for p in properties],
    'intensity_mean':  [p.intensity_mean          for p in properties],
    'intensity_max':  [p.intensity_max          for p in properties],
    'centroid':  [p.centroid          for p in properties],
}
```

Error

```
1 frames

[/usr/local/lib/python3.7/dist-packages/skimage/measure/_regionprops.py](https://localhost:8080/#) in __getattr__(self, attr)
    270         else:
    271             raise AttributeError(
--> 272                 f"'{type(self)}' object has no attribute '{attr}'"
    273             )
    274 

AttributeError: '<class 'skimage.measure._regionprops.RegionProperties'>' object has no attribute 'intensity_mean'
```

**Comment by pwalczysko** [comment]
RFE: ``Display the statistics`` suggests to me that I would see a graph, but only a table is produced.
Maybe change the title to ``Print out the statistics table`` or similar ?

In summary, 1 RFE (this comment above) and one [error](https://github.com/ome/omero-guide-python/pull/36#issuecomment-1050845379)

**Comment by jburel** [comment]
@pwalczysko I forgot to list this PR. The problem should now be fixed

**Comment by pwalczysko** [comment]
```
AttributeError                            Traceback (most recent call last)

[<ipython-input-10-4dcb20ddfdab>](https://localhost:8080/#) in <module>()
      6     'orientation' :  [p.orientation          for p in properties],
      7     'eccentricity':  [p.eccentricity          for p in properties],
----> 8     'intensity_max':  [p.intensity_max          for p in properties],
      9     'centroid':  [p.centroid          for p in properties],
     10 }

1 frames

[/usr/local/lib/python3.7/dist-packages/skimage/measure/_regionprops.py](https://localhost:8080/#) in __getattr__(self, attr)
    270         else:
    271             raise AttributeError(
--> 272                 f"'{type(self)}' object has no attribute '{attr}'"
    273             )
    274 

AttributeError: '<class 'skimage.measure._regionprops.RegionProperties'>' object has no attribute 'intensity_max'
```

I think that before it was erroring on intensity_mean, now on intensity_max

**Comment by jburel** [comment]
It looks like the version installed on Colab is older. I will revisit the notebook and install a new version in the notebook itself for colab

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-guides-push#500](https://latest-ci.openmicroscopy.org/jenkins/job/OMERO-guides-push/500/). See the [console output](https://latest-ci.openmicroscopy.org/jenkins/job/OMERO-guides-push/500/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - binder/environment.yml

~~--conflicts~~ Conflict resolved in build [OMERO-guides-push#667](https://latest-ci.openmicroscopy.org/jenkins/job/OMERO-guides-push/667/). See the [console output](https://latest-ci.openmicroscopy.org/jenkins/job/OMERO-guides-push/667/consoleText) for more details.

**Comment by pwalczysko** [comment]
Worked fine on

1. MyBinder
2. Google Colab
LGTM

**Review by pwalczysko — APPROVED** [review]

**Pull request merged**
