### PR TITLE
Binder

### PR DESCRIPTION
**Pull request by jburel**
* Add ability to run the repo independently of the full very large image available in training-notebooks.
* The notebooks were copied with the git history from training-notebooks
* This can be run:
  *  locally: see instructions in README
  * or in mybinder: use ``https://github.com/jburel/omero-guide-python``, branch: ``binder``

### CODE REVIEW

**Comment by pwalczysko** [comment]
MyBinder timed out for today - will continue tomorrow

**Comment by pwalczysko** [comment]
The HelloWorld notebook does not print "True" when successfully connected.

**Comment by pwalczysko** [comment]
The Simple FRAP script is processing just 2 images from the Dataset (the first two) and ignores the rest. Not sure why. The images are the same.

**Comment by pwalczysko** [comment]
Two comments, otherwise works fine on MyBinder.

**Comment by jburel** [comment]
@pwalczysko this is the same notebook that the one in training-notebooks.
Do you see the same behaviour on idr-analysis?

**Comment by pwalczysko** [comment]
> @pwalczysko this is the same notebook that the one in training-notebooks.
Do you see the same behaviour on idr-analysis?

Yes, the same behaviour on idr-analysis, also just 2 images.

**Comment by pwalczysko** [comment]
And the same behaviour when built locally as per README - the build and general behaviour is fine, the notebook simple FRAP also fine except it works only on 2 images.

**Comment by jburel** [comment]
Merging and working on setup

**Pull request merged**
