### PR TITLE
Break up simple_frap script

### PR DESCRIPTION
**Pull request by dominikl**
This PR breaks up the simple_frap script into a step-by-step way, like one would follow to script this from scratch. Each step builds on the previous one, but is completely self contained (can simply be copied and executed). I think that's much easier to follow along, especially in a workshop situation.
/cc @jburel @pwalczysko

### CODE REVIEW

**Comment by jburel** [comment]
The layout with code snippet collapsing/expanding did not work?

**Comment by dominikl** [comment]
Couldn't get that working, at least locally. But that's a bit limited anyway, as with the hide/expand approach you can't simulate "replacing" code, e.g. wrapping things into proper methods, etc.

**Comment by will-moore** [comment]
I think I understand the logic for this, but it makes any future editing of the script really hard.
Can we achieve something similar with the one script, annotated into steps (like the script 8)?

**Comment by jburel** [comment]
I am concerned too that breaking it into small portions will be difficult to edit, also people who want to start with a "full" existing example, will get have to copy several sections.
This is not the strategy we have followed elsewhere. Describing each step with "litteralinclude" has worked.

**Pull request closed without merging**
