### PR TITLE
Labels

### PR DESCRIPTION
**Pull request by jburel**
* Add stardist dependencies
* Add notebooks using stardist for prediction and display "zarr" labels and stardist predictions

to test run notebooks/zarr-public-s3-labels.ipynb
[stardist.mp4.zip](https://github.com/ome/omero-guide-python/files/5512580/stardist.mp4.zip)

### CODE REVIEW

**Comment by pwalczysko** [comment]
feedback on video in https://openmicroscopy.slack.com/archives/C011XLYFHUY/p1605023789000400

**Comment by pwalczysko** [comment]
Worked as expected. Only comment - if I would not have watched the video, I would have been surprised that there are no labels on first plane. Maybe the middle plane should be shown by default instead ?

**Comment by jburel** [comment]
The fact that there is no label, is b/c there is no label available in the original file.
I could switch to the middle z plane

**Comment by pwalczysko** [comment]
> The fact that there is no label, is b/c there is no label available in the original file.

Yes, you say that in the video.

> I could switch to the middle z plane

I think so

**Comment by pwalczysko** [comment]
Suggested some text changes in the notebook in https://github.com/jburel/omero-guide-python/pull/1 @jburel - if happy, maybe you could consider to merge

**Comment by jburel** [comment]
@pwalczysko I have renamed the new notebook to match  what is done in omero-guide-ilastik

**Review by pwalczysko — APPROVED** [review]

**Pull request merged**
